name: Deploy to AWS Lambda

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setting up AWS Credentials
        run: |
          pip install awscli
          aws configure set region us-east-1
          aws configure set output json
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} 
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
      - name: Create virtual env with Python
        run: |
          pip install virtualenv
          python3.10 -m virtualenv env
      - name: Install Requirements
        run: |
          . env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
      - name: Install Zappa
        run: |
          . env/bin/activate
          pip install zappa
          deactivate
      - name: Deploy/Update lambda
        run: |
          LAMBDA_ENV=prod
          if [[ "${{github.ref}}" == "refs/heads/develop" ]]; then
            LAMBDA_ENV=dev
          fi
                   
          echo -- Update $LAMBDA_ENV environment --
          . env/bin/activate
          
          zappa status $LAMBDA_ENV || NOT_DEPLOY=true
          if [ $NOT_DEPLOY == true ]; then          
            echo "The application is not deployed. Deploying..."
            zappa deploy $LAMBDA_ENV          
          else          
            echo "The application is deployed. Updating..."
            zappa update $LAMBDA_ENV          
          fi
          deactivate